### ISSUE TITLE
[oob-5.4-rc1] Build failed by online compiler

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-fat-filesystem#1]
## How to reproduce

1. Open online IDE
2. Press [Import] button
3. URL import
4. Source URL: ```https://github.com/ARMmbed/mbed-os-example-fat-filesystem```
5. Change mbed-os version to #3a27568 (origin/mbed-os-5.4)
6. Set any target
7. Build the project

```
Error: Cannot open source input file "FATFileSystem.h": No such file or directory in "main.cpp", Line: 2, Col: 28
```

**Comment by 0xc0170** [comment]
@theotherjimmy

**Comment by 0xc0170** [comment]
bump

**Comment by theotherjimmy** [comment]
That's definitely strange. Especially since I cannot reproduce the problem.

**Comment by theotherjimmy** [comment]
You are using the `oob_test_mbed-os-5.4` branch of this example, correct?

**Comment by toyowata** [comment]
@0xc0170 @theotherjimmy 
Sorry, my bad.  I could import the branch with hashed URL from online IDE such as:
```https://github.com/ARMmbed/mbed-os-example-fat-filesystem#9a5c348e9b835717041d23fa4d6266a241bb56b1```

And I could compile the example and worked fine.  I closed this ticket.
