### ISSUE TITLE
[oob 5.4] Executing IAR compiled binary on max32620 fills up dynamic memory

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-fat-filesystem#2]
ERROR:
```
Welcome to the filesystem example.
Formatting a FAT, RAM-backed filesystem. Failure. -5
Mounting the filesystem on "/fs". done.
Operator new out of memory
Opening a new file, numbers.txt.mbed assertation failed: obj->name != (PinName)NC, file: C:\Repos\mbed-os-example-fat-filesystem\mbed-os\targets\TARGET_Maxim\TARGET_MAX32620\gpio_object.h, line 1852402720
```

**Comment by c1728p9** [comment]
It looks like the max32620 only has a 16K heap for IAR:
https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_Maxim/TARGET_MAX32620/device/TOOLCHAIN_IAR/MAX32620.icf#L19

This is likely why the test is failing.

**Comment by MarceloSalazar** [comment]
I'm wondering if we could show a message in the console saying something like "Not enough HEAP memory"

**Comment by theotherjimmy** [comment]
Is that very similar to `Operator new out of memory` or am I imagining that?

**Comment by MarceloSalazar** [comment]
Sure. I don't think we can do much else apart from showing in the docs how much memory is required to run this example.

**Comment by 0xc0170** [comment]
> Sure. I don't think we can do much else apart from showing in the docs how much memory is required to run this example.

@theotherjimmy What do you think, would it make sense to document the requirements for this example? Or at least a note what is ideal minimum size required

**Comment by theotherjimmy** [comment]
Yes it makes sense to document the ideal minimum size.

**Comment by theotherjimmy** [comment]
Documented.

**Comment by theotherjimmy** [comment]
Closing. please re-open if you think this is not resolved.
