### ISSUE TITLE
Not getting full log output K66F

### ISSUE THREAD

**Issue by MattAtkinson** [ARMmbed/mbed-os-example-fat-filesystem#23]
I've tried this a few times on a K66F and had mixed results. I often just get:

> Welcome to the fWelcome to the filesystem example.
> Formatting a FAT, RAM-backedly. done.
> Dumping file to screen.
> 0
> 1
> 2
> 3

..and then I need to reflash the board and reopen the terminal to get any output again. This is usually the same, but I did once get up to 'EOF'. Other mbed boards I've used have printed to terminal correctly, so I doubt it's an issue with serial. I'm compiling on Win10, and used both arm and gcc_arm compilers. Tried both tera term and putty for terminal.

**Comment by adbridge** [comment]
@MattAtkinson Can you try a different K66F and/or make sure the drivers are up to date ? I just tried on windows 10, built using GCC_ARM, mbed-cli v1.2.0 , putty 9600 baud. Ran it 5 times in succession perfectly.....

**Comment by MattAtkinson** [comment]
> 9600 baud
My bad, I didn't change this assuming it was the same as the other mbed boards/examples I've used (and I was getting something comprehensible out of it rather than just junk).
