### ISSUE TITLE
File write and read back errors

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [ARMmbed/mbed-os-example-fat-filesystem#33]
Using this example project with small modifications, file writes fail after several kilobytes.

Please checkout my branch which demonstrates the error:
https://github.com/bmcdonnell-ionx/mbed-os-example-fat-filesystem/tree/demo-error

(You'll have to direct your serial output, or grab my [demo-err-usbserial](https://github.com/bmcdonnell-ionx/mbed-os-example-fat-filesystem/tree/demo-err-usbserial) branch if you're also using the EA LPC4088-QSB.)

Details are in the code comments, also quoted below. I don't know if there's any relation to the micro I'm using, but it's noted here in case there is.

```
// Failures using NXP LPC4088 micro, on Embedded Artists' LPC4088 QuickStart Board:
//
// - With mbed online compiler, 2017-12-08 (armcc):
//   - error writing at line 5974 (~35 KiB)
//   - file readback ends early after line 5888 (~512 bytes fewer)
//
// - With NXP MCUXpresso IDE v10.1.0 [Build 589] [2017-11-14]
//   (gcc-arm-none-eabi):
//   - error writing at line 4779 (~28 KiB)
//   - file readback ends early after line 4608 (~1 KiB fewer)

// 6 characters per line (4 digits + "\r\n")
// * 10000 lines = 60 KB, should fit on 128 * 512 = 64 KiB block device
#define NUM_INTS         (10000)
#define FIELD_WIDTH_STR  "4"

HeapBlockDevice bd(128 * 512, 512);
```

**Comment by theotherjimmy** [comment]
@bmcdonnell-ionx It sounds like the heap block device cannot allocate an entire 64KB block device. Your platform has 64KB of RAM, and the example uses 10KB RAM pre-allocated with GCC. This number does not include your stacks. You cannot expect to use all 64K of your device for the block device, and It's going to use some of the block device to store the File Allocation Table (FAT). I would expect this behavior.

**Comment by bmcdonnell-ionx** [comment]
@theotherjimmy, according to [the datasheet](https://www.nxp.com/docs/en/data-sheet/LPC408X_7X.pdf), the chip has 96 KB SRAM, but upon closer inspection (section 7.8 Memory Map), I see that the address space is not contiguous, so I guess it can only use the main 64 KB area for heap, which I think means you're essentially right. (Also, in my exported project, ld is identifying the 16 KB areas as "USB_RAM" and "ETH_RAM".)

For my reference, what do you mean by this part?

> the example uses 10KB RAM pre-allocated with GCC.

**Comment by theotherjimmy** [comment]
@bmcdonnell-ionx That's correct.

> the example uses 10KB RAM pre-allocated with GCC.

```
Link: fat-fs
Elf2Bin: fat-fs
+------------------+-------+-------+------+
| Module           | .text | .data | .bss |
+------------------+-------+-------+------+
| [fill]            |    96 |     4 |   35 |
| [lib]/c.a        | 35555 |  2572 |   94 |
| [lib]/gcc.a      |  3250 |     0 |    0 |
| [lib]/misc       |   196 |    12 |   25 |
| main.o           |  1011 |     4 |  140 |
| mbed-os/drivers  |   160 |     0 |    0 |
| mbed-os/features | 17484 |     4 |  336 |
| mbed-os/hal      |  1485 |     4 |   66 |
| mbed-os/platform |  3301 |    20 |  651 |
| mbed-os/rtos     |  8719 |   168 | 5989 |
| mbed-os/targets  |  3196 |    16 |   16 |
| Subtotals        | 74453 |  2804 | 7352 |
+------------------+-------+-------+------+
Total Static RAM memory (data + bss): 10156 bytes
Total Flash memory (text + data): 77257 bytes
```

The Total Static RAM memory at the bottom indicates how much RAM the compile allocated for global variables and static local variables.
