### ISSUE TITLE
Format returns -9 error code

### ISSUE THREAD

**Issue by kseverinkangas-zg** [ARMmbed/mbed-os-example-fat-filesystem#38]
### Description
- Type: Bug
- Priority: Critical

---------------------------------------------------------------
## Bug

**Target**
K64F

**Toolchain:**
GCC_ARM, ARM

**Toolchain version:**

**mbed-cli version:** 
1.1.1

**mbed-os sha:**
f4274b4 (HEAD, tag: mbed-os-5.7.0-rc3) Updating mbed-os to mbed-os-5.7.0-rc3

**DAPLink version:**

**Expected behavior**
Formatting and mounting works without errors.
Also printing should work.
**Actual behavior**
Formatting returns error code -9.
Printing does not work.
**Steps to reproduce**
run example

**Comment by bigw00d** [comment]
It works fine with mbed-os-5.7.6.(Target:K22F, Toolchain:GCC_ARM)
